name: Bug report 🐛
description: Create a report to help us improve our codebase.
labels: ["category.bug", "status.needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Welcome to Taiko :drum:
          <br>
        The issue tracker is for reporting bugs and feature requests for our dApps and client software only.
        If you have issues with campaigns or other non-technical issues, please reach out on our [Discord] (https://discord.gg/taikoxyz/)
          
        All new/updated issues are triaged regularly by the maintainers.
          <br>
        #### DO NOT FILE ISSUES FOR GENERAL SUPPORT QUESTIONS.
        Those will be closed without any comment and may be reported to GitHub as spam.
         
          
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Please make sure your report is unique and has not been reported previously
      options:
        - label: Yes, I've searched for similar issues on [GitHub](https://github.com/taikoxyz/) and didn't find any.
          required: true

  - type: textarea
    id: what_did_you_do
    attributes:
      label: What did you do?
      description: |
        How to write a good bug report?

        - Respect the issue template as much as possible.
        - The title should be short and descriptive.
        - Explain the conditions which led you to report this issue: the context.
        - The context should lead to something, an idea or a problem that you’re facing.
        - Remain clear and concise.
        - Format your messages to help the reader focus on what matters and understand the structure of your message, use [Markdown syntax](https://help.github.com/articles/github-flavored-markdown)
      placeholder: What did you do?
    validations:
      required: true

  - type: textarea
    id: what_did_you_see
    attributes:
      label: What did you see instead? If it was an error, please paste the error message or provide a screenshot.
      placeholder: What did you see instead?
    validations:
      required: true
      
  - type: checkboxes
    id: terms
    attributes:
      label: Spam policy
      description: By submitting this issue, you understand that SPAM issues will be closed and REPORTED to GitHub, which can close your account.
      options:
        - label: I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.
          required: true
