contact_links:
    - name: General Community support
      url: https://discord.gg/taikoxyz
      about: This issue tracker is only for feature requests and bug reports. If you have general questions, e.g. problems with campaings, the community support is available on Discord!
