name: Feature request 💡
description: Request a feature
labels: ["category.enhancement", "status.needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Before submitting, please check if an existing issue already exists. Thanks for taking the time to improve Taiko!
  
            
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Please make sure your feature request is unique and has not been requested previously
      options:
        - label: Yes, I've searched for similar issues on [GitHub](https://github.com/taikoxyz/) and didn't find any.
          required: true
      label: Do not request to integrate with other projects unless you are a representative of them. Then you should use the ecosystem application
      options:
        - label: I confirm, that I do not request he integration of a third party project.

  - type: textarea
    id: description
    attributes:
      label: Describe the feature request
      description: A concise description of what the problem and proposed solution is.
      value: Description of the feature request here.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Spam policy
      description: By submitting this issue, you understand that SPAM issues will be closed and REPORTED to GitHub, which can close your account.
      options:
        - label: I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.
          required: true
